export {
  getAuth,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  signInWithCredential,
  signOut,
  sendPasswordResetEmail,
  sendEmailVerification,
  updateProfile,
  updateEmail,
  updatePassword,
  deleteUser,
  reload,
  onAuthStateChanged,
  linkWithCredential,
  PhoneAuthProvider,
  signInWithPhoneNumber,
  getIdToken,
  EmailAuthProvider,
  GoogleAuthProvider,
  AppleAuthProvider,
  reauthenticateWithCredential,
  getAdditionalUserInfo,
} from "@react-native-firebase/auth";
